// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCagFFaHM6hO49fYgvedtC8k6E798ezo3g',
    appId: '1:360567637085:web:12699b163a061fc490f9b4',
    messagingSenderId: '360567637085',
    projectId: 'artbot-c3973',
    authDomain: 'artbot-c3973.firebaseapp.com',
    storageBucket: 'artbot-c3973.appspot.com',
    measurementId: 'G-7Q1VXH019H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBBw4WMwPpwhWEhUBYf8BIUpL6T26iZLQ',
    appId: '1:360567637085:android:01042d74d7e80c7c90f9b4',
    messagingSenderId: '360567637085',
    projectId: 'artbot-c3973',
    storageBucket: 'artbot-c3973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8DOC0jZ5I4R3PKDFrvE4MZu2E_ewWLQQ',
    appId: '1:360567637085:ios:8c1b3b9c6e30188690f9b4',
    messagingSenderId: '360567637085',
    projectId: 'artbot-c3973',
    storageBucket: 'artbot-c3973.appspot.com',
    iosBundleId: 'com.example.artbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8DOC0jZ5I4R3PKDFrvE4MZu2E_ewWLQQ',
    appId: '1:360567637085:ios:8c1b3b9c6e30188690f9b4',
    messagingSenderId: '360567637085',
    projectId: 'artbot-c3973',
    storageBucket: 'artbot-c3973.appspot.com',
    iosBundleId: 'com.example.artbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCagFFaHM6hO49fYgvedtC8k6E798ezo3g',
    appId: '1:360567637085:web:b27e25950e0b2f7990f9b4',
    messagingSenderId: '360567637085',
    projectId: 'artbot-c3973',
    authDomain: 'artbot-c3973.firebaseapp.com',
    storageBucket: 'artbot-c3973.appspot.com',
    measurementId: 'G-MZ998WMDQQ',
  );
}
